CREATE TABLE aluno (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       cpf VARCHAR(255),
                       email VARCHAR(255),
                       nome VARCHAR(255),
                       PRIMARY KEY (id)
);